apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pythonapi-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/neyoobaba/minikube-terraform"
    targetRevision: HEAD
    path: pythonapi-project
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true