image:
  repository: neyoobaba/pythonapi
  tag: 3b320fc
  pullPolicy: IfNotPresent
replicaCount: 2
service:
  type: ClusterIP
  port: 9001
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false