image:
  repository: neyoobaba/pythonapi
  tag: fa301e1
  pullPolicy: IfNotPresent
replicaCount: 4
service:
  type: ClusterIP
  port: 9001
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false