image:
  repositoy: neyoobaba/pythonapi
  tag: 9c45417
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9001
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false