image:
  repository: neyoobaba/pythonapi
  tag: 6949491
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9001
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false