image:
  repository: neyoobaba/pythonapi
  tag: 8c8481c
  pullPolicy: IfNotPresent
replicaCount: 3
service:
  type: ClusterIP
  port: 9001
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false