---

name: Complete DevOpse Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      - name: Build Docker Image
        run: |
          cd app
          docker build -t neyoobaba/pythonapi:${{ env.SHORT_SHA }} .
      - name: Login to Dockerhub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push Image to Dockerhub
        run: |
          docker push neyoobaba/pythonapi:${{ env.SHORT_SHA }}
      - name: Configure Git Author
        run: |
          git config --local user.email "hello@gmail.com"
          git config --local user.name "neyoobaba"
      - name: Update Helm Chart with new image tag
        run: |
          echo $PWD
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./pythonapi-project/values.yaml
          git add ./pythonapi-project/values.yaml
          git commit -m "Updated image tag to ${{ env.SHORT_SHA }}" 
          git push 